---
- name: Copy ssh keys to server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  with_items:
    - deploy_id_ed25519
    - deploy_id_ed25519.pub

- name: ansible ssh connections directory
  ansible.builtin.file:
    path: /root/.ssh/connections
    state: directory

- name: Create config file for root ssh
  ansible.builtin.template:
    src: ssh_config.j2
    dest: "/root/.ssh/config"
    owner: root
    group: root
    mode: 0640

- name: Ensure github.com is a known host
  ansible.builtin.lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Remove directory for clone
  ansible.builtin.file:
    path: /var/www/site
    state: absent
  when: bootstrap | default(false)

- name: Git checkout
  ansible.builtin.git:
    repo: 'git@example-alias:thedevdojo/wave.git'
    dest: /var/www/site
    clone: yes
    depth: 1
    update: yes
    force: yes

- name: Copy env file over
  ansible.builtin.template:
    src: laravel_env.j2
    dest: "/var/www/site/.env"
    owner: www-data
    group: www-data
    mode: 0640

- name: Make sure the laravel directory is owned by www-data
  ansible.builtin.file:
    path: /var/www
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Composer install
  become: yes
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/site
    cmd: composer install

- name: Run any database migrations
  become: yes
  become_user: www-data
  ansible.builtin.shell:
    chdir: /var/www/site
    cmd: yes | php artisan migrate
  run_once: true

- name: Run any db seed
  become: yes
  become_user: www-data
  ansible.builtin.shell:
    chdir: /var/www/site
    cmd: yes | php artisan db:seed
    creates: /var/www/seed_has_run
  run_once: true

- name: Touch a file so the seed is only run once.
  ansible.builtin.file:
    path: /var/www/seed_has_run
    state: touch
    mode: u=rw,g=r,o=r


